### ISSUE TITLE
Missing files: sun_icon2.png and outline_icon2.png

### ISSUE THREAD

**Issue by FastThenLeft** [ac2cz/KlaTrack#16]
I thought I might work on some of the bugs/enhancements and when I went to build it, I found that there are two missing files in the repository:
sun_icon2.png
outline_icon2.png

That also made me worry that the repository might not have the latest files. I didn't want to start debugging old versions.

Could you please check that everything is up-to-date?

**Comment by ac2cz** [comment]
Sorry for the delayed response.  Thanks for looking at some of the bugs.

When I run without the icons it starts up and defaults to the labels.  But I agree that the two files were not checked into the master branch.  I just pushed them to the repository.

All of the icons are in a directory called images.  At run time they need to be in the same directory as the jar or main class.

**Comment by FastThenLeft** [comment]
Thanks Chris! Java isn't a language I know, but it's close enough to
C++that I should be able to pick it up quickly.

Thanks!
-David, N9KT

**Comment by ac2cz** [comment]
Ok, sounds good.  I am using Eclipse as the IDE.  That may make things easier.  If you need instructions or help to compile I am happy to supply.  The key is to make sure that the dependencies in the lib directory are included in the class path when you compile and run.

**Comment by FastThenLeft** [comment]
I too have this same error (and a bunch of friends that have installed the program after I've shown it to them). It happens when the Keps are older than 24 hours. I can trigger it reliably if I "touch" the nasabare.txt file and make it 25 hours old, and then run the program.

In my testing, it also seems like if the keps are older than a week, then it works.

I've started to debug it. Here's the output in case it's evident to you. The error is triggered by line 188 of SatManager.java. The error creates a zero-byte nasabare.txt file and therefore the program displays no satellites.

$ java -jar KlaTrack.jar 
Downloading new keps ..
.. keps are current
 ... open output file ../home/david/KLATrack/nasabare.txt
 ... getting file ..
SERIOUS ERROR - Uncaught and thrown from GUI
java.lang.NullPointerException
	at java.base/sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:766)
	at com.g0kla.track.SatManager.fetchTLEFile(SatManager.java:188)
	at com.g0kla.track.SatManager.loadTLEFile(SatManager.java:125)
	at com.g0kla.track.SatManager.<init>(SatManager.java:53)
	at com.g0kla.track.gui.MainWindow.<init>(MainWindow.java:267)
	at com.g0kla.track.TrackMain$1.run(TrackMain.java:98)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
